spring:
  application:
    name: e-commerce-backend
  docker:
    compose:
      enabled: true
      file: ../compose.yaml
      start:
        command: "up"
        arguments: "--build"
      stop:
        command: "down"
        arguments:
          - "--remove-orphans"
          - "--volumes"

app:
  jwt:
    secret: team26-super-secret-jwt-signing-key-dev-only-32chars
    expiration: 86400000
