services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
    volumes:
      - ./db-setup:/docker-entrypoint-initdb.d
  frontend:
    build:
      context: ./e-commerce-frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./e-commerce-frontend/src:/app/src
      - /app/node_modules

